# Generated by Django 4.2.21 on 2025-05-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("client", "Клиент"),
                    ("admin", "Админ"),
                    ("owner", "Владелец"),
                ],
                default="client",
                max_length=10,
                verbose_name="Уровень доступа",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="activity_history",
            field=models.JSONField(
                blank=True, default=list, verbose_name="История активности"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Адресс"),
        ),
        migrations.AlterField(
            model_name="user",
            name="allergies",
            field=models.TextField(blank=True, verbose_name="Аллергии"),
        ),
        migrations.AlterField(
            model_name="user",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Баланс"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Почта"),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(blank=True, max_length=10, verbose_name="Пол"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_subscribed",
            field=models.BooleanField(default=True, verbose_name="Подписан"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False, verbose_name="Пройдена верификация"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Был в сети"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="user",
            name="loyalty_discount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="Скидка"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, unique=True, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="preferred_contact_method",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Предпочтительный способ связи"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="referral_code",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Реферальный код",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата регистрации"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="social_media_links",
            field=models.JSONField(blank=True, default=dict, verbose_name="Соц. сети"),
        ),
        migrations.AlterField(
            model_name="user",
            name="source_of_signup",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Откуда узнал о нас"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="special_notes",
            field=models.TextField(blank=True, verbose_name="Заметки"),
        ),
        migrations.AlterField(
            model_name="user",
            name="transaction_history",
            field=models.JSONField(
                blank=True, default=list, verbose_name="История транзакций"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, verbose_name="Логин"),
        ),
        migrations.AlterField(
            model_name="user",
            name="visits_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Кол-во посещений"
            ),
        ),
    ]
