# Generated by Django 4.2.21 on 2025-05-26 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0007_alter_studio_who_admin"),
        ("users", "0004_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="source_of_signup",
        ),
        migrations.AddField(
            model_name="user",
            name="where_admin",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="studio.studio",
                verbose_name="Администратор",
            ),
        ),
    ]
