# Generated by Django 4.2.21 on 2025-06-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_source_of_signup_user_where_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="source_of_signup",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Источник регистрации",
            ),
        ),
    ]
