# Generated by Django 4.2.21 on 2025-06-05 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_source_of_signup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="source_of_signup",
        ),
    ]
