# Generated by Django 5.2.3 on 2025-07-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_user_source_of_signup"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type_client",
            field=models.CharField(
                choices=[("guest", "Гость"), ("regular", "Постоянник")],
                default="guest",
                verbose_name="Тип клиента",
            ),
        ),
    ]
