# Generated by Django 5.2.3 on 2025-07-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_type_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tariff",
            field=models.CharField(
                choices=[("S", "S"), ("M", "M"), ("L", "L")],
                max_length=1,
                null=True,
                verbose_name="Тариф",
            ),
        ),
    ]
