# Generated by Django 4.2.21 on 2025-05-14 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studio",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="studio",
            name="description",
            field=models.TextField(verbose_name="Описании студии"),
        ),
        migrations.AlterField(
            model_name="studio",
            name="phone_number",
            field=models.CharField(
                max_length=255, verbose_name="Номер телефона студии"
            ),
        ),
        migrations.AlterField(
            model_name="studio",
            name="who_admin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Администратор",
            ),
        ),
    ]
