# Generated by Django 4.2.21 on 2025-05-15 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studio", "0002_alter_studio_address_alter_studio_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studio",
            name="who_admin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Администратор",
            ),
        ),
    ]
