# Generated by Django 4.2.21 on 2025-05-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0004_alter_studio_who_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studio",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Номер телефона студии"
            ),
        ),
    ]
