# Generated by Django 4.2.21 on 2025-05-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0005_alter_studio_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studio",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Номер телефона студии",
            ),
        ),
    ]
