# Generated by Django 4.2.21 on 2025-05-26 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studio", "0006_alter_studio_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studio",
            name="who_admin",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Администратор",
            ),
        ),
    ]
